# Generated by Django 5.0.3 on 2024-03-12 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('ciudad', models.CharField(max_length=64)),
                ('direccion', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Recital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banda_artista', models.CharField(max_length=64)),
                ('horario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('apellido', models.CharField(max_length=64)),
                ('recitales', models.ManyToManyField(blank=True, related_name='usuario', to='recitales.recital')),
            ],
        ),
    ]
