# Generated by Django 5.0.3 on 2024-03-14 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('ciudad', models.CharField(max_length=64)),
                ('direccion', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Recital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banda_artista', models.CharField(max_length=64)),
                ('fecha', models.DateField()),
                ('horario', models.TimeField()),
                ('precio', models.IntegerField()),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lugar', to='recitales.establecimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_entradas', models.IntegerField()),
                ('recital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recital', to='recitales.recital')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('apellido', models.CharField(max_length=64)),
                ('reservas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='recitales.reserva')),
            ],
        ),
    ]
