# Generated by Django 5.0.3 on 2024-03-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recitales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recital',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
